-- +goose Up
SELECT create_hypertable('ipld.blocks', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.tip_sets', 'height', migrate_data => true, chunk_time_interval => 100800);
SELECT create_hypertable('filecoin.tip_set_members', 'height', migrate_data => true, chunk_time_interval => 20160);
SELECT create_hypertable('filecoin.block_headers', 'height', migrate_data => true, chunk_time_interval => 20160);
SELECT create_hypertable('filecoin.block_parents', 'height', migrate_data => true, chunk_time_interval => 20160);
SELECT create_hypertable('filecoin.block_messages', 'height', migrate_data => true, chunk_time_interval => 32768);
SELECT create_hypertable('filecoin.messages', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.parsed_messages', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.internal_messages', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.internal_parsed_messages', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.vm_messages', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.receipts', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.drand_block_entries', 'height', migrate_data => true, chunk_time_interval => 100800);
SELECT create_hypertable('filecoin.actors', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.actor_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.actor_events', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.init_actor_id_addresses', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.cron_actor_method_receivers', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.reward_actor_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.account_actor_addresses', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_actor_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_actor_deal_proposals', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_actor_deal_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_actor_pending_proposals', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_actor_escrows', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_actor_deal_ops_buckets', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_actor_deal_ops_at_epoch', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_actor_locked_tokens', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.miner_actor_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.miner_infos', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.miner_vesting_funds', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.miner_deadlines', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.miner_pre_committed_sector_infos', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.miner_sector_infos', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.miner_partitions', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.miner_partition_expirations', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.multisig_actor_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.multisig_pending_txs', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.payment_channel_actor_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.payment_channel_lane_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_power_actor_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_power_cron_event_buckets', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_power_cron_events', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_power_claims', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_power_proof_validation_buckets', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.storage_power_proof_seal_verify_infos', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.verified_registry_actor_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.verified_registry_verifiers', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.verified_registry_clients', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.fevm_actor_state', 'height', migrate_data => true, chunk_time_interval => 2880);
SELECT create_hypertable('filecoin.fevm_actor_storage', 'height', migrate_data => true, chunk_time_interval => 2880);

-- update version
INSERT INTO public.db_version (singleton, version) VALUES (true, 'v0.0.0-h')
ON CONFLICT (singleton) DO UPDATE SET (version, tstamp) = ('v0.0.0-h', NOW());

-- +goose Down
INSERT INTO public.db_version (singleton, version) VALUES (true, 'v0.0.0')
ON CONFLICT (singleton) DO UPDATE SET (version, tstamp) = ('v0.0.0', NOW());

-- reversing conversion to hypertable requires migrating all data from every chunk back to a single table
-- create new regular tables
CREATE TABLE ipld.blocks_i (LIKE ipld.blocks INCLUDING ALL);
CREATE TABLE filecoin.tip_sets_i (LIKE filecoin.tip_sets INCLUDING ALL);
CREATE TABLE filecoin.tip_set_members_i (LIKE filecoin.tip_set_members INCLUDING ALL);
CREATE TABLE filecoin.block_headers_i (LIKE filecoin.block_headers INCLUDING ALL);
CREATE TABLE filecoin.block_parents_i (LIKE filecoin.block_parents INCLUDING ALL);
CREATE TABLE filecoin.block_messages_i (LIKE filecoin.block_messages INCLUDING ALL);
CREATE TABLE filecoin.messages_i (LIKE filecoin.messages INCLUDING ALL);
CREATE TABLE filecoin.parsed_messages_i (LIKE filecoin.parsed_messages INCLUDING ALL);
CREATE TABLE filecoin.internal_messages_i (LIKE filecoin.internal_messages INCLUDING ALL);
CREATE TABLE filecoin.internal_parsed_messages_i (LIKE filecoin.internal_parsed_messages INCLUDING ALL);
CREATE TABLE filecoin.vm_messages_i (LIKE filecoin.vm_messages INCLUDING ALL);
CREATE TABLE filecoin.receipts_i (LIKE filecoin.receipts INCLUDING ALL);
CREATE TABLE filecoin.drand_block_entries_i (LIKE filecoin.drand_block_entries INCLUDING ALL);
CREATE TABLE filecoin.actors_i (LIKE filecoin.actors INCLUDING ALL);
CREATE TABLE filecoin.actor_state_i (LIKE filecoin.actor_state INCLUDING ALL);
CREATE TABLE filecoin.actor_events_i (LIKE filecoin.actor_events INCLUDING ALL);
CREATE TABLE filecoin.init_actor_id_addresses_i (LIKE filecoin.init_actor_id_addresses INCLUDING ALL);
CREATE TABLE filecoin.cron_actor_method_receivers_i (LIKE filecoin.cron_actor_method_receivers INCLUDING ALL);
CREATE TABLE filecoin.reward_actor_state_i (LIKE filecoin.reward_actor_state INCLUDING ALL);
CREATE TABLE filecoin.account_actor_addresses_i (LIKE filecoin.account_actor_addresses INCLUDING ALL);
CREATE TABLE filecoin.storage_actor_state_i (LIKE filecoin.storage_actor_state INCLUDING ALL);
CREATE TABLE filecoin.storage_actor_deal_proposals_i (LIKE filecoin.storage_actor_deal_proposals INCLUDING ALL);
CREATE TABLE filecoin.storage_actor_deal_state_i (LIKE filecoin.storage_actor_deal_state INCLUDING ALL);
CREATE TABLE filecoin.storage_actor_pending_proposals_i (LIKE filecoin.storage_actor_pending_proposals INCLUDING ALL);
CREATE TABLE filecoin.storage_actor_escrows_i (LIKE filecoin.storage_actor_escrows INCLUDING ALL);
CREATE TABLE filecoin.storage_actor_deal_ops_buckets_i (LIKE filecoin.storage_actor_deal_ops_buckets INCLUDING ALL);
CREATE TABLE filecoin.storage_actor_deal_ops_at_epoch_i (LIKE filecoin.storage_actor_deal_ops_at_epoch INCLUDING ALL);
CREATE TABLE filecoin.storage_actor_locked_tokens_i (LIKE filecoin.storage_actor_locked_tokens INCLUDING ALL);
CREATE TABLE filecoin.miner_actor_state_i (LIKE filecoin.miner_actor_state INCLUDING ALL);
CREATE TABLE filecoin.miner_infos_i (LIKE filecoin.miner_infos INCLUDING ALL);
CREATE TABLE filecoin.miner_vesting_funds_i (LIKE filecoin.miner_vesting_funds INCLUDING ALL);
CREATE TABLE filecoin.miner_deadlines_i (LIKE filecoin.miner_deadlines INCLUDING ALL);
CREATE TABLE filecoin.miner_pre_committed_sector_infos_i (LIKE filecoin.miner_pre_committed_sector_infos INCLUDING ALL);
CREATE TABLE filecoin.miner_sector_infos_i (LIKE filecoin.miner_sector_infos INCLUDING ALL);
CREATE TABLE filecoin.miner_partitions_i (LIKE filecoin.miner_partitions INCLUDING ALL);
CREATE TABLE filecoin.miner_partition_expirations_i (LIKE filecoin.miner_partition_expirations INCLUDING ALL);
CREATE TABLE filecoin.multisig_actor_state_i (LIKE filecoin.multisig_actor_state INCLUDING ALL);
CREATE TABLE filecoin.multisig_pending_txs_i (LIKE filecoin.multisig_pending_txs INCLUDING ALL);
CREATE TABLE filecoin.payment_channel_actor_state_i (LIKE filecoin.payment_channel_actor_state INCLUDING ALL);
CREATE TABLE filecoin.payment_channel_lane_state_i (LIKE filecoin.payment_channel_lane_state INCLUDING ALL);
CREATE TABLE filecoin.storage_power_actor_state_i (LIKE filecoin.storage_power_actor_state INCLUDING ALL);
CREATE TABLE filecoin.storage_power_cron_event_buckets_i (LIKE filecoin.storage_power_cron_event_buckets INCLUDING ALL);
CREATE TABLE filecoin.storage_power_cron_events_i (LIKE filecoin.storage_power_cron_events INCLUDING ALL);
CREATE TABLE filecoin.storage_power_claims_i (LIKE filecoin.storage_power_claims INCLUDING ALL);
CREATE TABLE filecoin.storage_power_proof_validation_buckets_i (LIKE filecoin.storage_power_proof_validation_buckets INCLUDING ALL);
CREATE TABLE filecoin.storage_power_proof_seal_verify_infos_i (LIKE filecoin.storage_power_proof_seal_verify_infos INCLUDING ALL);
CREATE TABLE filecoin.verified_registry_actor_state_i (LIKE filecoin.verified_registry_actor_state INCLUDING ALL);
CREATE TABLE filecoin.verified_registry_verifiers_i (LIKE filecoin.verified_registry_verifiers INCLUDING ALL);
CREATE TABLE filecoin.verified_registry_clients_i (LIKE filecoin.verified_registry_clients INCLUDING ALL);
CREATE TABLE filecoin.fevm_actor_state_i (LIKE filecoin.fevm_actor_state INCLUDING ALL);
CREATE TABLE filecoin.fevm_actor_storage_i (LIKE filecoin.fevm_actor_storage INCLUDING ALL);

-- migrate data
INSERT INTO ipld.blocks_i (SELECT * FROM ipld.blocks);
INSERT INTO filecoin.tip_sets_i (SELECT * FROM filecoin.tip_sets);
INSERT INTO filecoin.tip_set_members_i (SELECT * FROM filecoin.tip_set_members);
INSERT INTO filecoin.block_headers_i (SELECT * FROM filecoin.block_headers);
INSERT INTO filecoin.block_parents_i (SELECT * FROM filecoin.block_parents);
INSERT INTO filecoin.block_messages_i (SELECT * FROM filecoin.block_messages);
INSERT INTO filecoin.messages_i (SELECT * FROM filecoin.messages);
INSERT INTO filecoin.parsed_messages_i (SELECT * FROM filecoin.parsed_messages);
INSERT INTO filecoin.internal_messages_i (SELECT * FROM filecoin.internal_messages);
INSERT INTO filecoin.internal_parsed_messages_i (SELECT * FROM filecoin.internal_parsed_messages);
INSERT INTO filecoin.vm_messages_i (SELECT * FROM filecoin.vm_messages);
INSERT INTO filecoin.receipts_i (SELECT * FROM filecoin.receipts);
INSERT INTO filecoin.drand_block_entries_i (SELECT * FROM filecoin.drand_block_entries);
INSERT INTO filecoin.actors_i (SELECT * FROM filecoin.actors);
INSERT INTO filecoin.actor_state_i (SELECT * FROM filecoin.actor_state);
INSERT INTO filecoin.actor_events_i (SELECT * FROM filecoin.actor_events);
INSERT INTO filecoin.init_actor_id_addresses_i (SELECT * FROM filecoin.init_actor_id_addresses);
INSERT INTO filecoin.cron_actor_method_receivers_i (SELECT * FROM filecoin.cron_actor_method_receivers);
INSERT INTO filecoin.reward_actor_state_i (SELECT * FROM filecoin.reward_actor_state);
INSERT INTO filecoin.account_actor_addresses_i (SELECT * FROM filecoin.account_actor_addresses);
INSERT INTO filecoin.storage_actor_state_i (SELECT * FROM filecoin.storage_actor_state);
INSERT INTO filecoin.storage_actor_deal_proposals_i (SELECT * FROM filecoin.storage_actor_deal_proposals);
INSERT INTO filecoin.storage_actor_deal_state_i (SELECT * FROM filecoin.storage_actor_deal_state);
INSERT INTO filecoin.storage_actor_pending_proposals_i (SELECT * FROM filecoin.storage_actor_pending_proposals);
INSERT INTO filecoin.storage_actor_escrows_i (SELECT * FROM filecoin.storage_actor_escrows);
INSERT INTO filecoin.storage_actor_deal_ops_buckets_i (SELECT * FROM filecoin.storage_actor_deal_ops_buckets);
INSERT INTO filecoin.storage_actor_deal_ops_at_epoch_i (SELECT * FROM filecoin.storage_actor_deal_ops_at_epoch);
INSERT INTO filecoin.storage_actor_locked_tokens_i (SELECT * FROM filecoin.storage_actor_locked_tokens);
INSERT INTO filecoin.miner_actor_state_i (SELECT * FROM filecoin.miner_actor_state);
INSERT INTO filecoin.miner_infos_i (SELECT * FROM filecoin.miner_infos);
INSERT INTO filecoin.miner_vesting_funds_i (SELECT * FROM filecoin.miner_vesting_funds);
INSERT INTO filecoin.miner_deadlines_i (SELECT * FROM filecoin.miner_deadlines);
INSERT INTO filecoin.miner_pre_committed_sector_infos_i (SELECT * FROM filecoin.miner_pre_committed_sector_infos);
INSERT INTO filecoin.miner_sector_infos_i (SELECT * FROM filecoin.miner_sector_infos);
INSERT INTO filecoin.miner_partitions_i (SELECT * FROM filecoin.miner_partitions);
INSERT INTO filecoin.miner_partition_expirations_i (SELECT * FROM filecoin.miner_partition_expirations);
INSERT INTO filecoin.multisig_actor_state_i (SELECT * FROM filecoin.multisig_actor_state);
INSERT INTO filecoin.multisig_pending_txs_i (SELECT * FROM filecoin.multisig_pending_txs);
INSERT INTO filecoin.payment_channel_actor_state_i (SELECT * FROM filecoin.payment_channel_actor_state);
INSERT INTO filecoin.payment_channel_lane_state_i (SELECT * FROM filecoin.payment_channel_lane_state);
INSERT INTO filecoin.storage_power_actor_state_i (SELECT * FROM filecoin.storage_power_actor_state);
INSERT INTO filecoin.storage_power_cron_event_buckets_i (SELECT * FROM filecoin.storage_power_cron_event_buckets);
INSERT INTO filecoin.storage_power_cron_events_i (SELECT * FROM filecoin.storage_power_cron_events);
INSERT INTO filecoin.storage_power_claims_i (SELECT * FROM filecoin.storage_power_claims);
INSERT INTO filecoin.storage_power_proof_validation_buckets_i (SELECT * FROM filecoin.storage_power_proof_validation_buckets);
INSERT INTO filecoin.storage_power_proof_seal_verify_infos_i (SELECT * FROM filecoin.storage_power_proof_seal_verify_infos);
INSERT INTO filecoin.verified_registry_actor_state_i (SELECT * FROM filecoin.verified_registry_actor_state);
INSERT INTO filecoin.verified_registry_verifiers_i (SELECT * FROM filecoin.verified_registry_verifiers);
INSERT INTO filecoin.verified_registry_clients_i (SELECT * FROM filecoin.verified_registry_clients);
INSERT INTO filecoin.fevm_actor_state_i (SELECT * FROM filecoin.fevm_actor_state);
INSERT INTO filecoin.fevm_actor_storage_i (SELECT * FROM filecoin.fevm_actor_storage);

-- drop hypertables
DROP TABLE  ipld.blocks;
DROP TABLE  filecoin.tip_sets;
DROP TABLE  filecoin.tip_set_members;
DROP TABLE  filecoin.block_headers;
DROP TABLE  filecoin.block_parents;
DROP TABLE  filecoin.block_messages;
DROP TABLE  filecoin.messages;
DROP TABLE  filecoin.parsed_messages;
DROP TABLE  filecoin.internal_messages;
DROP TABLE  filecoin.internal_parsed_messages;
DROP TABLE  filecoin.vm_messages;
DROP TABLE  filecoin.receipts;
DROP TABLE  filecoin.drand_block_entries;
DROP TABLE  filecoin.actors;
DROP TABLE  filecoin.actor_state;
DROP TABLE  filecoin.actor_events;
DROP TABLE  filecoin.init_actor_id_addresses;
DROP TABLE  filecoin.cron_actor_method_receivers;
DROP TABLE  filecoin.reward_actor_state;
DROP TABLE  filecoin.account_actor_addresses;
DROP TABLE  filecoin.storage_actor_state;
DROP TABLE  filecoin.storage_actor_deal_proposals;
DROP TABLE  filecoin.storage_actor_deal_state;
DROP TABLE  filecoin.storage_actor_pending_proposals;
DROP TABLE  filecoin.storage_actor_escrows;
DROP TABLE  filecoin.storage_actor_deal_ops_buckets;
DROP TABLE  filecoin.storage_actor_deal_ops_at_epoch;
DROP TABLE  filecoin.storage_actor_locked_tokens;
DROP TABLE  filecoin.miner_actor_state;
DROP TABLE  filecoin.miner_infos;
DROP TABLE  filecoin.miner_vesting_funds;
DROP TABLE  filecoin.miner_deadlines;
DROP TABLE  filecoin.miner_pre_committed_sector_infos;
DROP TABLE  filecoin.miner_sector_infos;
DROP TABLE  filecoin.miner_partitions;
DROP TABLE  filecoin.miner_partition_expirations;
DROP TABLE  filecoin.multisig_actor_state;
DROP TABLE  filecoin.multisig_pending_txs;
DROP TABLE  filecoin.payment_channel_actor_state;
DROP TABLE  filecoin.payment_channel_lane_state;
DROP TABLE  filecoin.storage_power_actor_state;
DROP TABLE  filecoin.storage_power_cron_event_buckets;
DROP TABLE  filecoin.storage_power_cron_events;
DROP TABLE  filecoin.storage_power_claims;
DROP TABLE  filecoin.storage_power_proof_validation_buckets;
DROP TABLE  filecoin.storage_power_proof_seal_verify_infos;
DROP TABLE  filecoin.verified_registry_actor_state;
DROP TABLE  filecoin.verified_registry_verifiers;
DROP TABLE  filecoin.verified_registry_clients;
DROP TABLE  filecoin.fevm_actor_state;
DROP TABLE  filecoin.fevm_actor_storage;

-- rename new tables
ALTER TABLE ipld.blocks_i RENAME TO blocks;
ALTER TABLE filecoin.tip_sets_i RENAME TO tip_sets;
ALTER TABLE filecoin.tip_set_members_i RENAME TO tip_set_members;
ALTER TABLE filecoin.block_headers_i RENAME TO block_headers;
ALTER TABLE filecoin.block_parents_i RENAME TO block_parents;
ALTER TABLE filecoin.block_messages_i RENAME TO block_messages;
ALTER TABLE filecoin.messages_i RENAME TO messages;
ALTER TABLE filecoin.parsed_messages_i RENAME TO parsed_messages;
ALTER TABLE filecoin.internal_messages_i RENAME TO internal_messages;
ALTER TABLE filecoin.internal_parsed_messages_i RENAME TO internal_parsed_messages;
ALTER TABLE filecoin.vm_messages_i RENAME TO vm_messages;
ALTER TABLE filecoin.receipts_i RENAME TO receipts;
ALTER TABLE filecoin.drand_block_entries_i RENAME TO drand_block_entries;
ALTER TABLE filecoin.actors_i RENAME TO actors;
ALTER TABLE filecoin.actor_state_i RENAME TO actor_state;
ALTER TABLE filecoin.actor_events_i RENAME TO actor_events;
ALTER TABLE filecoin.init_actor_id_addresses_i RENAME TO init_actor_id_addresses;
ALTER TABLE filecoin.cron_actor_method_receivers_i RENAME TO cron_actor_method_receivers;
ALTER TABLE filecoin.reward_actor_state_i RENAME TO reward_actor_state;
ALTER TABLE filecoin.account_actor_addresses_i RENAME TO account_actor_addresses;
ALTER TABLE filecoin.storage_actor_state_i RENAME TO storage_actor_state;
ALTER TABLE filecoin.storage_actor_deal_proposals_i RENAME TO storage_actor_deal_proposals;
ALTER TABLE filecoin.storage_actor_deal_state_i RENAME TO storage_actor_deal_state;
ALTER TABLE filecoin.storage_actor_pending_proposals_i RENAME TO storage_actor_pending_proposals;
ALTER TABLE filecoin.storage_actor_escrows_i RENAME TO storage_actor_escrows;
ALTER TABLE filecoin.storage_actor_deal_ops_buckets_i RENAME TO storage_actor_deal_ops_buckets;
ALTER TABLE filecoin.storage_actor_deal_ops_at_epoch_i RENAME TO storage_actor_deal_ops_at_epoch;
ALTER TABLE filecoin.storage_actor_locked_tokens_i RENAME TO storage_actor_locked_tokens;
ALTER TABLE filecoin.miner_actor_state_i RENAME TO miner_actor_state;
ALTER TABLE filecoin.miner_infos_i RENAME TO miner_infos;
ALTER TABLE filecoin.miner_vesting_funds_i RENAME TO miner_vesting_funds;
ALTER TABLE filecoin.miner_deadlines_i RENAME TO miner_deadlines;
ALTER TABLE filecoin.miner_pre_committed_sector_infos_i RENAME TO miner_pre_committed_sector_infos;
ALTER TABLE filecoin.miner_sector_infos_i RENAME TO miner_sector_infos;
ALTER TABLE filecoin.miner_partitions_i RENAME TO miner_partitions;
ALTER TABLE filecoin.miner_partition_expirations_i RENAME TO miner_partition_expirations;
ALTER TABLE filecoin.multisig_actor_state_i RENAME TO multisig_actor_state;
ALTER TABLE filecoin.multisig_pending_txs_i RENAME TO multisig_pending_txs;
ALTER TABLE filecoin.payment_channel_actor_state_i RENAME TO payment_channel_actor_state;
ALTER TABLE filecoin.payment_channel_lane_state_i RENAME TO payment_channel_lane_state;
ALTER TABLE filecoin.storage_power_actor_state_i RENAME TO storage_power_actor_state;
ALTER TABLE filecoin.storage_power_cron_event_buckets_i RENAME TO storage_power_cron_event_buckets;
ALTER TABLE filecoin.storage_power_cron_events_i RENAME TO storage_power_cron_events;
ALTER TABLE filecoin.storage_power_claims_i RENAME TO storage_power_claims;
ALTER TABLE filecoin.storage_power_proof_validation_buckets_i RENAME TO storage_power_proof_validation_buckets;
ALTER TABLE filecoin.storage_power_proof_seal_verify_infos_i RENAME TO storage_power_proof_seal_verify_infos;
ALTER TABLE filecoin.verified_registry_actor_state_i RENAME TO verified_registry_actor_state;
ALTER TABLE filecoin.verified_registry_verifiers_i RENAME TO verified_registry_verifiers;
ALTER TABLE filecoin.verified_registry_clients_i RENAME TO verified_registry_clients;
ALTER TABLE filecoin.fevm_actor_state_i RENAME TO fevm_actor_state;
ALTER TABLE filecoin.fevm_actor_storage_i RENAME TO fevm_actor_storage;
